#!/usr/bin/env bash

DEFAULT_WEB_SERVER_PORT=${DEFAULT_WEB_SERVER_PORT:-8000}
DEFAULT_WEB_SOCKET_PORT=${DEFAULT_WEB_SOCKET_PORT:-25482}

omnidb-server -p $DEFAULT_WEB_SERVER_PORT \
              -w $DEFAULT_WEB_SOCKET_PORT
